"""Cubase MIDI Remote bridge for cubase-mcp on Windows (loopMIDI port "Cubase MCP").

This file is the single source of truth for the MIDI protocol between server.py and Cubase.
Run it to (re)generate the Cubase MIDI Remote script:

    .venv\\Scripts\\python.exe wardogs_remote.py

Protocol (all Control Change):
  mixer tracks 1-16  -> MIDI channel = track - 1:  CC7 volume, CC10 pan, CC20 mute, CC21 solo
  commands           -> MIDI channel 16, CC 40 + index into COMMANDS, value 127 = press
"""
import os
import pathlib
import xml.etree.ElementTree as ET

PORT_PREFIX = 'Cubase MCP'
MIXER_TRACKS = 16
CC_VOLUME, CC_PAN, CC_MUTE, CC_SOLO = 7, 10, 20, 21
COMMAND_CHANNEL = 15
COMMAND_CC_BASE = 40

# (tool name, Key Commands category, Key Commands name). Names are checked against
# Cubase's own Key Commands.xml when the script is generated.
COMMANDS = [
    ('play', 'Transport', 'Start'),
    ('stop', 'Transport', 'Stop'),
    ('record', 'Transport', 'Record'),
    ('return_to_zero', 'Transport', 'Return to Zero'),
    ('goto_end', 'Transport', 'Goto End'),
    ('cycle', 'Transport', 'Cycle'),
    ('metronome', 'Transport', 'Metronome On'),
    ('next_marker', 'Transport', 'Locate Next Marker'),
    ('previous_marker', 'Transport', 'Locate Previous Marker'),
    ('to_left_locator', 'Transport', 'To Left Locator'),
    ('locators_to_selection', 'Transport', 'Locators to Selection'),
    ('nudge_cursor_left', 'Transport', 'Nudge Cursor Left'),
    ('nudge_cursor_right', 'Transport', 'Nudge Cursor Right'),
    ('save', 'File', 'Save'),
    ('save_new_version', 'File', 'Save New Version'),
    ('import_midi_file', 'File', 'Import MIDI File'),
    ('export_audio_mixdown', 'File', 'Export Audio Mixdown'),
    ('undo', 'Edit', 'Undo'),
    ('redo', 'Edit', 'Redo'),
    ('select_all', 'Edit', 'Select All'),
    ('select_none', 'Edit', 'Select None'),
    ('duplicate', 'Edit', 'Duplicate'),
    ('delete', 'Edit', 'Delete'),
    ('mute_selected_events', 'Edit', 'Mute'),
    ('split_at_cursor', 'Edit', 'Split at Cursor'),
    ('open_close_editor', 'Edit', 'Open/Close Editor'),
    ('deactivate_all_solo', 'Edit', 'Deactivate All Solo'),
    ('quantize', 'MIDI', 'Quantize'),
    ('legato', 'MIDI', 'Legato'),
    ('zoom_in', 'Zoom', 'Zoom In'),
    ('zoom_out', 'Zoom', 'Zoom Out'),
    ('zoom_full', 'Zoom', 'Zoom Full'),
    ('zoom_to_selection', 'Zoom', 'Zoom to Selection'),
    ('select_previous_track', 'Navigate', 'Up'),
    ('select_next_track', 'Navigate', 'Down'),
    ('navigate_left', 'Navigate', 'Left'),
    ('navigate_right', 'Navigate', 'Right'),
    ('show_mixer', 'Devices', 'Mixer'),
    ('show_vst_instruments', 'Devices', 'VST Instruments'),
]
COMMAND_NAMES = [c[0] for c in COMMANDS]


def command_cc(name):
    return COMMAND_CC_BASE + COMMAND_NAMES.index(name)


def cubase_commands():
    """Every 'Category|Name' pair in the installed Cubase 14 Key Commands.xml."""
    path = pathlib.Path(os.environ['APPDATA']) / 'Steinberg' / 'Cubase 14_64' / 'Key Commands.xml'
    root = ET.parse(path).getroot()
    pairs = set()
    for cat in root.find("list[@name='Categories']"):
        cname = cat.find("string[@name='Name']").get('value')
        for cmd in cat.findall("list[@name='Commands']/item/string[@name='Name']"):
            pairs.add(f"{cname}|{cmd.get('value')}")
    return pairs


def build_script():
    js = [
        '// Generated by cubase-mcp/wardogs_remote.py - edit that file, not this one.',
        "var midiremote_api = require('midiremote_api_v1')",
        "var deviceDriver = midiremote_api.makeDeviceDriver('Wardogs', 'ClaudeBridge', 'Claude')",
        'var midiInput = deviceDriver.mPorts.makeMidiInput()',
        f"deviceDriver.makeDetectionUnit().detectSingleInput(midiInput).expectInputNameStartsWith('{PORT_PREFIX}')",
        "var page = deviceDriver.mMapping.makePage('Claude')",
        "var zone = page.mHostAccess.mMixConsole.makeMixerBankZone('Tracks')",
        '    .includeAudioChannels().includeInstrumentChannels().includeSamplerChannels().includeMIDIChannels()',
        '',
        'function control(kind, x, y, channel, cc) {',
        '    var c = kind === "knob" ? deviceDriver.mSurface.makeKnob(x, y, 1, 1)',
        '                            : deviceDriver.mSurface.makeButton(x, y, 1, 1)',
        '    c.mSurfaceValue.mMidiBinding.setInputPort(midiInput).bindToControlChange(channel, cc)',
        '    return c.mSurfaceValue',
        '}',
        '',
        f'for (var i = 0; i < {MIXER_TRACKS}; i++) {{',
        '    var ch = zone.makeMixerBankChannel().mValue',
        f'    page.makeValueBinding(control("knob", i, 0, i, {CC_VOLUME}), ch.mVolume)',
        f'    page.makeValueBinding(control("knob", i, 1, i, {CC_PAN}), ch.mPan)',
        f'    page.makeValueBinding(control("button", i, 2, i, {CC_MUTE}), ch.mMute)',
        f'    page.makeValueBinding(control("button", i, 3, i, {CC_SOLO}), ch.mSolo)',
        '}',
        '',
    ]
    for i, (_, cat, name) in enumerate(COMMANDS):
        x, y = i % MIXER_TRACKS, 5 + i // MIXER_TRACKS
        js.append(f'page.makeCommandBinding(control("button", {x}, {y}, {COMMAND_CHANNEL}, '
                  f'{COMMAND_CC_BASE + i}), {cat!r}, {name!r})')
    return '\n'.join(js) + '\n'


if __name__ == '__main__':
    known = cubase_commands()
    missing = [f'{c}|{n}' for _, c, n in COMMANDS if f'{c}|{n}' not in known]
    if missing:
        raise SystemExit(f'Not in Cubase Key Commands: {missing}')
    out = (pathlib.Path(os.environ['USERPROFILE']) / 'Documents' / 'Steinberg' / 'Cubase' / 'MIDI Remote'
           / 'Driver Scripts' / 'Local' / 'wardogs' / 'claudebridge' / 'wardogs_claudebridge.js')
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_script(), encoding='utf-8')
    print(f'{len(COMMANDS)} commands verified, wrote {out}')
