/*
  Social cards.

  The images are static files in public/og/, generated by scripts/make-og.mjs
  rather than by next/og: under `output: "export"` there is no server to render
  one on request, and a plain PNG cannot fail at share time.

  Paths are relative on purpose — `metadataBase` in app/layout.tsx makes them
  absolute, which is what every scraper needs. Change the domain in one place
  and every card follows.
*/

export type OgCard =
  | "default"
  | "simulator"
  | "videos"
  | "maps"
  | "terminology"
  | "guides"
  | "pilot-app";

/**
 * Spread into both `openGraph` and `twitter` so the two never disagree about
 * which picture a page has.
 */
export const ogCard = (name: OgCard, alt: string) => ({
  images: [{ url: `/og/${name}.png`, width: 1200, height: 630, alt }],
});
